name: ci
on: [push]
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm install
    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hi"
            - run: pwd
            - run: pwd
              working-directory: $GITHUB_WORKSPACE
            - run: npm run build
              working-directory: $GITHUB_WORKSPACE
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run: npm run test
              working-directory: $GITHUB_WORKSPACE
    lint:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run: npm run lint
              working-directory: $GITHUB_WORKSPACE
    prettier:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run: npx prettier --check index.html ./src/**/* ./test/**/*
              working-directory: $GITHUB_WORKSPACE
    typecheck:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - run: npx tsc --noEmit
              working-directory: $GITHUB_WORKSPACE
